spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
      active: dev
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
      map-underscore-to-camel-case: true

